name: Check Project Files Naming
on: 
  pull_request:
    branches:
      - main
      - timvdstap-patch-1
jobs:
  check_naming:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Filename Inspector Default
      id: scan-test-files
      uses: AbsaOSS/filename-inspector@v0.1.0
      with:
        name-patterns: 'yyyy-MM-dd_*'
        paths: | 
          **/data/**
          **/data/Aquafluor/**,
          **/data/DR1900/**,
          **/data/Instruments/**
        excludes: |
         **/data/Aquafluor/Changelog.txt
         **/data/DR1900/Changelog.txt
         **/data/Instruments/Changelog.txt
    - name: Notify failed build
      uses: jayqi/failed-build-issue-action@v1
      if: failure() && github.event.pull_request == null
      with:
        github-token: ${{ secrets.CI_TOKEN }}
